# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: |
      deb [arch={{ dpkg_arch }}] https://apt.releases.hashicorp.com \
      {{ ansible_distribution_release }} main
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install consul
  ansible.builtin.apt:
    name: consul=1.14.4-1
    state: present

- name: Configure /etc/consul.d/consul.hcl
  ansible.builtin.template:
    src: templates/consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: '0644'

- name: Copy CA cert to /etc/consul.d/
  ansible.builtin.copy:
    src: files/consul-agent-ca.pem
    dest: /etc/consul.d/consul-agent-ca.pem
    owner: consul
    group: consul
    mode: '0644'

- name: Copy CA key to /etc/consul.d/
  ansible.builtin.copy:
    src: files/consul-agent-ca-key.pem
    dest: /etc/consul.d/consul-agent-ca-key.pem
    owner: consul
    group: consul
    mode: '0644'

- name: Generate node private key
  community.crypto.openssl_privatekey:
    path: /etc/consul.d/node-key.pem
    curve: secp384r1
    type: ECC
    owner: consul
    group: consul

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: /etc/consul.d/node-csr.pem
    privatekey_path: /etc/consul.d/node-key.pem
    common_name: "server.{{ consul_datacenter }}.{{ consul_domain }}"
    owner: consul
    group: consul

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    provider: ownca
    ownca_path: /etc/consul.d/consul-agent-ca.pem
    ownca_privatekey_path: /etc/consul.d/consul-agent-ca-key.pem
    path: /etc/consul.d/node-cert.pem
    privatekey_path: /etc/consul.d/node-key.pem
    csr_path: /etc/consul.d/node-csr.pem
    owner: consul
    group: consul

- name: Enable and start consul
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: consul

- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present
  when: consul_role == 'server'

- name: Copy bind defaults to /etc/default/named
  ansible.builtin.copy:
    src: files/named
    dest: /etc/default/named
    owner: root
    group: root
    mode: '0644'
  when: consul_role == 'server'

- name: Get all default bind configs
  ansible.builtin.find:
    path: "/etc/bind/"
    excludes: 'named.conf'
  register: cleanup
  when: consul_role == 'server'

- name: Delete all default bind configs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ cleanup.files }}"
  when: consul_role == 'server'

- name: Configure /etc/bind/named.conf
  ansible.builtin.template:
    src: templates/named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0644'
  when: consul_role == 'server'

- name: Restart bind9
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: bind9
  when: consul_role == 'server'
