# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- name: Set up Gluster Servers
  hosts: all
  become: true

  roles:
    - glusterfs

- name: Install docker
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      vars:
        docker_edition: "ce"
        docker_package_state: "present"
        docker_service_manage: true
        docker_service_state: started
        docker_service_enabled: true
        docker_restart_handler_state: restarted

- name: Set up Consul Servers
  hosts: all
  become: true

  roles:
    - role: consul
      consul_role: server

- name: Set up Nomad Cluster
  hosts: all
  become: true

  roles:
    - role: nomad
      nomad_role: server
