# -*- mode: ansible -*-
# vi: set ft=ansible :
---
nomad_datacenter: "homelab"
nomad_data_dir: "/opt/consul"
nomad_role: "server"
nomad_version: "1.4.3-1"

nfs_mount: "/mnt/nfs/videos"

cni_path: "/opt/cni/bin"
cni_version: "1.2.0"
arch: "{{ ansible_architecture }}"
dpkg_arch: "{{ 'amd64' if arch == 'x86_64' else arch }}"
nfs_idmap_conf: "home.jpopa.com"
