# -*- mode: ansible -*-
# vi: set ft=ansible :
---

- name: Install docker
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      vars:
        docker_edition: "ce"
        docker_package_state: "present"
        docker_service_manage: true
        docker_service_state: started
        docker_service_enabled: true
        docker_restart_handler_state: restarted

- name: Install DataDog
  hosts: all
  become: true

  roles:
    - datadog.datadog
  vars:
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
    datadog_site: "us5.datadoghq.com"
    datadog_additional_groups: docker, nomad, consul, bind, gluster


- name: Set up all nodes
  hosts: all
  become: true

  roles:
    - glusterfs
    - consul
    - nomad
