# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- name: Install parted
  ansible.builtin.apt:
    name: parted
    state: present

- name: Create 100% size partition on {{ brick_disk }}
  community.general.parted:
    device: "{{ brick_disk }}"
    number: 1
    state: present
    fs_type: "{{ partition_format }}"
    part_end: '100%'

- name: Format filesystem on {{ brick_partition }}  # noqa args
  community.general.filesystem:
    fstype: "{{ partition_format }}"
    dev: "{{ brick_partition }}"

- name: Create directory at {{ partition_mount_path }}}
  ansible.builtin.file:
    path: "{{ partition_mount_path }}"
    state: directory
    mode: '0755'

- name: Mount created partition to {{ partition_mount_path }}
  ansible.posix.mount:
    boot: true
    path: "{{ partition_mount_path }}"
    src: "{{ brick_partition }}"
    fstype: "{{ partition_format }}"
    opts: noatime
    state: mounted

- name: Create directory {{ brick_path }}
  ansible.builtin.file:
    path: "{{ brick_path }}"
    state: directory
    mode: '0755'

- name: Install glusterfs
  ansible.builtin.include_role:
    name: geerlingguy.glusterfs
  vars:
    glusterfs_ppa_use: false

- name: Create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    bricks: "{{ brick_path }}"
    replicas: 3
    cluster: "{{ groups['gluster_server'] }}"
  run_once: true

- name: Create directory to mount gluster volume to
  ansible.builtin.file:
    path: "{{ gluster_mount_path }}"
    state: directory
    mode: '0755'

- name: Mount gluster volume
  ansible.posix.mount:
    boot: true
    name: "{{ gluster_mount_path }}"
    src: "{{ inventory_hostname }}:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev,noatime"
    state: mounted
