# -*- mode: ansible -*-
# vi: set ft=ansible :
---
consul_datacenter: "homelab"
consul_domain: "consul"
consul_data_dir: "/opt/consul"
consul_encrypt: ""
consul_role: "server"
consul_ui_enabled: true
consul_acl_policy: "deny"
consul_connect_enabled: true

consul_port_grpc: 8502
consul_port_grpc_tls: 8503
consul_port_dns: 8600
consul_port_http: 8500
consul_port_https: 8501
consul_port_serf_lan: 8301
consul_port_serf_wan: 8302
consul_port_server: 8300
consul_port_sidecar_min: 21000
consul_port_sidecar_max: 21255

dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
