# -*- mode: ansible -*-
# vi: set ft=ansible :
---
brick_disk: "/dev/sda"
brick_partition: "{{ brick_disk }}1"
partition_mount_path: "/mnt/nvme"
brick_path: "{{ partition_mount_path }}/brick0"
partition_format: "ext4"
gluster_volume_name: "gluster"
gluster_mount_path: "/mnt/{{ gluster_volume_name }}"
