# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- name: Restart consul
  ansible.builtin.systemd:
    name: consul
    state: restarted
- name: Restart bind9
  ansible.builtin.systemd:
    name: bind9
    state: restarted
