# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- name: Restart nomad
  ansible.builtin.systemd:
    name: nomad
    state: restarted

- name: Clear nfsidmap
  ansible.builtin.command:
    cmd: "nfsidmap -c"
  changed_when: false

- name: Mount nfs volume {{ nfs_mount }}
  ansible.posix.mount:
    boot: true
    name: "{{ nfs_mount }}"
    src: "{{ nfs_server }}:{{ nfs_path }}"
    fstype: nfs4
    opts: "rsize=16384,wsize=16384,hard,timeo=600,retrans=2,noatime,rw"
    state: remounted
