# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_arch }}] \
    https://apt.releases.hashicorp.com \
    {{ ansible_distribution_release }} main"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install nomad
  ansible.builtin.apt:
    name: nomad={{ nomad_version }}
    state: present
  notify: Restart nomad

- name: Configure /etc/nomad.d/nomad.hcl
  ansible.builtin.template:
    src: templates/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: '0644'
  notify: Restart nomad

# make directory for cni plugins
- name: Make directory for cni plugins
  ansible.builtin.file:
    path: "{{ cni_path }}"
    state: directory
    owner: nomad
    group: nomad
    mode: '0755'

- name: Download cni plugins from github and extract into {{ cni_path }}
  ansible.builtin.unarchive:
    src: "https://github.com/containernetworking/plugins/releases/\
    download/v{{ cni_version }}/cni-plugins-linux-{{ dpkg_arch }}-v\
    {{ cni_version }}.tgz"
    dest: "{{ cni_path }}"
    remote_src: true
    owner: nomad
    group: nomad
    mode: '0755'

- name: Enable and start nomad
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: nomad

- name: Mount nfs volume {{ nfs_mount }}
  ansible.posix.mount:
    boot: true
    name: "{{ nfs_mount }}"
    src: "{{ nfs_server }}:{{ nfs_path }}"
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
    state: mounted
