# .github/workflows/deploy.yml

name: Deploy # name of the action (displayed in the github interface)

on: # event list
  push: # on a push to each of these branches
    branches:
      - main

jobs: # list of things to do
  linting:
    name: Deploying # job name (unique id)
    runs-on: self-hosted # on which machine to run
    steps: # list of steps to run

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Populate hosts.ini from secrets
        run: |
          echo "[nodes]" > hosts.ini
          echo "${{ secrets.HOMELAB_NODES }}" >> hosts.ini

      - name: Populate consul CA files from secrets
        run: |
          echo "${{ secrets.CONSUL_AGENT_CA }}" > roles/consul/files/consul-agent-ca.pem
          echo "${{ secrets.CONSUL_AGENT_CA_KEY }}" > roles/consul/files/consul-agent-ca-key.pem

      - name: Set consul_encrypt value in roles/consul/defaults/main.yml
        run: |
          echo "consul_encrypt: ${{ secrets.CONSUL_ENCRYPT }}" >> roles/consul/defaults/main.yml

      - name: Run ansible playbook
        run: |
          ansible-playbook -i hosts.ini deploy.yml